name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: maddenlockin
          POSTGRES_PASSWORD: Doris555!
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:
        CI: true
        DATABASE_URL: postgres://maddenlockin:Doris555!@postgres:5432/postgres